apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend
  labels:
    app: dashboard-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-frontend
  template:
    metadata:
      labels:
        app: dashboard-frontend
    spec:
      containers:
        - name: dashboard-frontend
          image: dashboard-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend
spec:
  selector:
    app: dashboard-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
